### ISSUE TITLE
Location field in the JobsByMail form does not work.

### ISSUE THREAD

**Issue by TiSiE** [yawik/JobsByMail#1]
The field is neither prefilled with an existing selection, nor can one select anything.

**Comment by fedys** [comment]
I know about this problem. There are many other problems in the commit. I wrote about it to @cbleek . This commit was only meant as a preview of an incomplete task.

**Comment by fedys** [comment]
fixed with 2303d73a408797dc3b54f8a4b058e2864b5cb84c

**Comment by TiSiE** [comment]
1. This issue was not meant to discredit your valuable work in any way, merely a way to remind me and others that there is something, which does not work. It was not in particular meant to force you to work on this matter IMMEDIATELY...

2. It's just another part of the "Yay-a-new-feature-let's-pull-it-in-even-it's-not-ready-yet"-way of @cbleek :)

**Comment by fedys** [comment]
@TiSiE okay :)

**Comment by fedys** [comment]
fixed with 2303d73a408797dc3b54f8a4b058e2864b5cb84c
